version: "3.9"
services:
  app:
    image: go_minting
    build:
      dockerfile: docker/go_minting/Dockerfile
      args:
        - target=dev
    volumes:
      - .:/app
    ports:
      - "18080:8080"
