openapi: 3.0.0
x-stoplight:
  id: 62mgbclbf0v2y
info:
  title: go-minting-api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /nfts:
    post:
      summary: ''
      operationId: create-nft
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  tokenId:
                    type: number
                    minimum: 1
              examples:
                Example 1:
                  value:
                    tokenId: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Example 1:
                  value:
                    message: Bad Request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Example 1:
                  value:
                    message: internal server error
      description: Create New NFT
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                userSig:
                  type: string
                name:
                  type: string
                description:
                  type: string
                files:
                  type: string
            examples:
              Example 1:
                value:
                  userSig: 4.556527834825534e+155
                  name: nft name
                  description: nft discription
                  files: files
components:
  schemas:
    Nft:
      title: Nft
      x-stoplight:
        id: 5pucyxtanetse
      type: object
      properties:
        id:
          type: string
        tokenId:
          type: string
        metadataUrl:
          type: string
        contract:
          $ref: '#/components/schemas/Contract'
    Contract:
      title: Contract
      x-stoplight:
        id: k1xsyul7v82sh
      type: object
      properties:
        id:
          type: string
        contractAddress:
          type: string
        chainId:
          type: number
  requestBodies: {}
